name: tcpdump-snap
base: core18 # the base snap is the execution environment for this snap
version: '1.1' 
summary: tcpdump packet analyser
description: |
  A snap package for tcpdump/libpcap

grade: stable 
confinement: strict

apps:
  tcpdump:
     command: sbin/tcpdump
     plugs:
       - network-control
       - hardware-observe
       - firewall-control

parts:
  libpcap:
    source: https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz
    plugin: autotools
    build-packages:
       - flex
       - bison
    stage-packages:
       - flex
       - bison
  tcpdump:
    source: https://www.tcpdump.org/release/tcpdump-4.9.3.tar.gz
    plugin: autotools 
    after:
      - libpcap
